defaults:
  - _self_
  - data: dogs
  - model: mdogs
  - paths: default
  - callbacks: default
  - logger: default
  - trainer: default

paths:
  output_dir: ${hydra:runtime.cwd}/outputs

ckpt_path: ${paths.output_dir}
input_path: ${paths.data_dir}/dogs_dataset/dataset/validation/
output_path: ${hydra:runtime.cwd}/validation_results/

num_images: 5
