FROM satyajitghana/pytorch:2.3.1

WORKDIR /app

ADD . /app

RUN pip install --no-cache-dir fastapi[standard]==0.114.1 python-multipart==0.0.9 pillow==10.4.0

EXPOSE 8000

ENV MODEL_PATH=/app/model_checkpoint.pth

CMD ["uvicorn", "serve:app", "--host", "0.0.0.0", "--port", "8000"]
